# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Superdan
email: dongdan@xiaodongdan.com
description: > # this means to ignore newlines until "baseurl:"
  stay hungry, stay foolish
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://xiaodongdan.com" # the base hostname & protocol for your site
#twitter_username: jekyllrb
github_username:  xdongdan

# Build settings
markdown: kramdown
highlighted: pygments
permalink: /:title

gems: [jekyll-paginate]
paginate: 10
paginate_path: "blog/page:num"


